# Book settings
title: Economic Dynamics 
author: John Stachurski
logo: logo.png


sphinx:
  config:
    mathjax3_config:
      tex:
        macros:
          "Exp" : ["\\operatorname{Exp}"]
          "Binomial" : ["\\operatorname{Binomial}"]
          "Poisson" : ["\\operatorname{Poisson}"]
          "BB" : ["\\mathbb{B}"]
          "EE" : ["\\mathbb{E}"]
          "PP" : ["\\mathbb{P}"]
          "RR" : ["\\mathbb{R}"]
          "NN" : ["\\mathbb{N}"]
          "ZZ" : ["\\mathbb{Z}"]
          "dD" : ["\\mathcal{D}"]
          "fF" : ["\\mathcal{F}"]
          "lL" : ["\\mathcal{L}"]
          "linop" : ["\\mathcal{L}(\\mathbb{B})"]
          "linopell" : ["\\mathcal{L}(\\ell_1)"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js                    

execute:
  execute_notebooks: cache
  timeout: -1

latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
